WindowManager:
    MainWindow:
    ResultsWindow:

<MainWindow>:
    name: "main"
    GridLayout:
        cols: 1
        size_hint: (0.6, 0.8)
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

        Image:
            source: "logo.png"
            size_hint: (1.5,1.5)
        Label:
            id: hello_label
            text: "Hello! What can I calculate for you?"
            color: "white"
        TextInput:
            id: path_input
            hint_text: "\n Paste here path to your csv file..."
            size_hint: (1,0.5)
            bold: True
            halign: "center"
            valign: "middle"
        Button:
            text: "Calculate"
            size_hint: (1,0.5)
            bold: True
            on_press: root.calculate()

        Button:
            id: results_button
            text: "Results"
            size_hint: (1,0.5)
            bold: True
            background_color: "#00ffbf"
            disabled: True
            on_release:
                app.root.current = "results"
                root.manager.transition.direction = "left"
<ResultsWindow>:
    name: "results"
    GridLayout:
        cols: 1
        TextInput:
            id: label_res
            text: "select buttons to view the results:"
            size_hint: (1.5,1.5)
            multiline: True
        GridLayout:
            cols: 4
            size_hint: (1,0.5)
            Button:
                text: "Allel Frequencies"
                on_press: root.show_allel()
            Button:
                text: "Genotype Frequencies"
                on_press: root.show_gene()
            Button:
                text: "Heterozygosity"
                on_press: root.show_hetero()
            Button:
                text: "F Statistics"
                on_press: root.show_f()
        Button:
            text: "Save xlsx"
            size_hint: (1,0.2)
        Button:
            text: "Back"
            size_hint: (1,0.2)
            on_release:
                app.root.current = "main"
                root.manager.transition.direction = "right"